// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPOXB5rfgLjZhi80mr9oZEIzVRiiZpk9Y',
    appId: '1:1008402942918:web:0de7ead39b29b0093400c7',
    messagingSenderId: '1008402942918',
    projectId: 'organizamais-fe8f4',
    authDomain: 'organizamais-fe8f4.firebaseapp.com',
    storageBucket: 'organizamais-fe8f4.firebasestorage.app',
    measurementId: 'G-PHWDEZD6ZN',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCPOXB5rfgLjZhi80mr9oZEIzVRiiZpk9Y',
    appId: '1:1008402942918:web:0de7ead39b29b0093400c7',
    messagingSenderId: '1008402942918',
    projectId: 'organizamais-fe8f4',
    authDomain: 'organizamais-fe8f4.firebaseapp.com',
    storageBucket: 'organizamais-fe8f4.firebasestorage.app',
    measurementId: 'G-PHWDEZD6ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYfWESeKc52_NhmAjWcCkaWluxXjpqsM',
    appId: '1:1008402942918:android:bcb0e827db887fc43400c7',
    messagingSenderId: '1008402942918',
    projectId: 'organizamais-fe8f4',
    storageBucket: 'organizamais-fe8f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6y7RHyPuIJX_etf9nliInYgenI21yBlA',
    appId: '1:1008402942918:ios:126e3ad52efe94c73400c7',
    messagingSenderId: '1008402942918',
    projectId: 'organizamais-fe8f4',
    storageBucket: 'organizamais-fe8f4.firebasestorage.app',
    iosClientId: '1008402942918-misvegur2pr77p855au4ql7q51m1ih6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.organizamais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6y7RHyPuIJX_etf9nliInYgenI21yBlA',
    appId: '1:1008402942918:ios:126e3ad52efe94c73400c7',
    messagingSenderId: '1008402942918',
    projectId: 'organizamais-fe8f4',
    storageBucket: 'organizamais-fe8f4.firebasestorage.app',
    iosClientId: '1008402942918-misvegur2pr77p855au4ql7q51m1ih6s.apps.googleusercontent.com',
    iosBundleId: 'com.example.organizamais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPOXB5rfgLjZhi80mr9oZEIzVRiiZpk9Y',
    appId: '1:1008402942918:web:e74d63214b9934063400c7',
    messagingSenderId: '1008402942918',
    projectId: 'organizamais-fe8f4',
    authDomain: 'organizamais-fe8f4.firebaseapp.com',
    storageBucket: 'organizamais-fe8f4.firebasestorage.app',
    measurementId: 'G-78TNW5GYRL',
  );
}
